-- MySQL Script generated by MySQL Workbench
-- Sat 04 Mar 2017 06:18:54 PM EST
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema ece1779
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema ece1779
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `ece1779` DEFAULT CHARACTER SET utf8 ;
USE `ece1779` ;

-- -----------------------------------------------------
-- Table `ece1779`.`users`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ece1779`.`users` ;

CREATE TABLE IF NOT EXISTS `ece1779`.`users` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `login` VARCHAR(16) NOT NULL,
  `password` VARCHAR(16) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ece1779`.`images`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ece1779`.`images` ;

CREATE TABLE IF NOT EXISTS `ece1779`.`images` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `userId` INT NOT NULL,
  `key1` VARCHAR(255) NOT NULL,
  `key2` VARCHAR(255) NOT NULL,
  `key3` VARCHAR(255) NOT NULL,
  `key4` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_images_1_idx` (`userId` ASC),
  CONSTRAINT `fk_images_1`
    FOREIGN KEY (`userId`)
    REFERENCES `ece1779`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
